name: python-helloworld

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: set-up
      uses: actions/checkout@v2
      with:
        username: ${{ secrets.DOCKERUSERNAME }}
        password: ${{ secrets.DOCKERAPIKEY }}
        
    - name: Build the Docker image
      run: docker build .
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERUSERNAME }}:latest
      
