name: python-helloworld

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    -   name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERUSERNAME}}
          password: ${{ secrets.DOCKERAPIKEY }}
          
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: neethumohan1212/helloworld:latest
        
      
#     - name: Build and push
#       id: docker_build
#       uses: docker/build-push-action@v2
#       with:
#           context: ./
#           file: ./Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKERUSERNAME }}:latest
      
